mssql_database:
  server: KRR-TST-PAHWL02
  user_id: EUROPE\%LOGIN%
  password: "%PASSWORD%"
  database: KRR-PA-DEV-Development

postgres_reports:
  host: KRR-SQL-PSGRE00
  port: 5432
  user: "%LOGIN%"
  password: "%PASSWORD%"
  dbname: krr-pa-analytics-data
  sslmode: disable  

postgres_data:
  host: KRR-SQL-PSGRE00
  port: 5432
  user: "%LOGIN%"
  password: "%PASSWORD%"
  dbname: krr-pa-raw-data
  sslmode: disable

type_ms: "mssql"
type_pg: "postgres"

querries:
  consumption_mnlz: "SELECT * FROM public.get_cast_iron_consumption_mnlz('%s')"
  consumption_ingot: "SELECT * FROM public.get_cast_iron_consumption_ingot('%s')"
  meltdowns_onrs: "SELECT * FROM public.get_number_of_meltdowns_onrs('%s')"
  scrap_consumption_mnlz: "SELECT * FROM public.get_scrap_consumption_mnlz('%s')"
  scrap_consumption_ingot: "SELECT * FROM public.get_scrap_consumption_ingot('%s')"
  get_data: "SELECT * FROM public.get_data('%s', %d)"
  get_data_greater_than_zero: "SELECT * FROM public.get_data_greater_than_zero('%s', %d)"
  get_slag_truncation: "SELECT * FROM public.get_slag_truncation('%s')"
  get_pheroalloy_mnlz: "SELECT * FROM public.get_pheroalloy_mnlz('%s', %d)"
  get_pheroalloy_ingot: "SELECT * FROM public.get_pheroalloy_ingot('%s', %d)"
  get_upk: "SELECT * FROM public.get_upk('%s', %d, %d)"
  get_good_cast_iron: "SELECT * FROM public.get_good_cast_iron('%s', %d)"
  get_inlet_temperature_oxidation: "SELECT * FROM public.get_inlet_temperature_oxidation('%s', %d, %d)"
  get_mnlz: "SELECT * FROM public.get_mnlz('%s', %d, %d)"

measurings:
  fl_heat_lf: 77851922
  w_heat: 77851923
  w_iron: 77851920
  w_lom: 77851924
  w_heat_mnlz: 77851927
  si_iron: 77851903
  t_iron: 77851904
  p_iron: 53253288
  oxi_bof: 77851909
  w_caov: 77851910
  w_dolo: 77851911
  w_alrz: 77851912
  w_smesrz: 77851913
  s_iron: 77851906
  w_fesi: 16772519
  fesi65: 16758519
  w_simn: 16778619
  simn: 23456445
  w_femn78: 16875211
  w_femn88: 16875213
  w_femn95: 16875214
  femn78: 16875217
  femn88: 16875218
  fl_heat_cutoff_slag: 16875224
  fl_slop: 16875231
  shl_mgo: 16875248
  w_fecr: 16875254
  w_fecr025: 16875255
  w_fecr800: 16875256
  tm_treatment: 13456745
  n_lf: 12375678
  m1e: 13455740
  m2e: 13455741
  m3e: 13455742
  m4e: 13455743
  m5e: 13455744
  m6e: 13455745
  m7e: 13455746
  m8e: 13455747
  w_cao_lf: 29897655
  w_cao90_lf: 29897656
  w_caf2_lf: 29897657
  w_apk_lf: 29897658
  t1: 29897659
  treatment: 29897660
  o2_1: 29897661
  avgspeed: 29897663
  ncasting: 29897664
  cnt_heat: 29897667
  pcount: 29897668
  weight_ls: 29897671
  weight_grossstart: 29897672
  weight_grossend: 29897673
  tm_between: 13456799
  ccm_begin: 13456787
  dtk: 13456753
  dtn: 13456754
  sample_time: 16273828
  heat_start: 16273829
  dt_begin: 16273830
  dt_end: 16273831
  s1_oil: 16273832
  s2_oil: 16273833
  s3_oil: 16273834
  s4_oil: 16273835
  s5_oil: 16273836
  s6_oil: 16273837
  dk_tap: 16273838
  end_series: 16273839
  serialization: 16273840
  n_ccm: 16273841
  energy1: 15890001
  energy2: 15890002
  energy3: 15890003
  energy4: 15890004
  energy5: 15890005
  energy6: 15890006
  energy7: 15890007
  energy8: 15890008
  temperature1: 16273842
  temperature2: 16273843
  temperature3: 16273844
  temperature4: 16273845
  temperature5: 16273846
  temperature6: 16273847
  steel_grade: 16273848

steel_temperatures:
  - steel_type: "1006"
    min: 1555
    max: 1570
  - steel_type: "1008"
    min: 1555
    max: 1570
  - steel_type: "4Si1"
    min: 1540
    max: 1550
  - steel_type: "C72D2"
    min: 1495
    max: 1510
  - steel_type: "70"
    min: 1495
    max: 1510
  - steel_type: "C80D2"
    min: 1480
    max: 1490
  - steel_type: "3Si1"
    min: 1540
    max: 1550
  - steel_type: "65"
    min: 1500
    max: 1515
  - steel_type: "75"
    min: 1490
    max: 1505
  - steel_type: "SV-08GA"
    min: 1555
    max: 1570
  - steel_type: "1005"
  - steel_type: "1006m"
    min: 1550
    max: 1565
  - steel_type: "1008m"
    min: 1550
    max: 1565
  - steel_type: "1010"
    min: 1550
    max: 1565
  - steel_type: "1060"
    min: 1500
    max: 1515
  - steel_type: "1070"
    min: 1495
    max: 1510
  - steel_type: "1075"
    min: 1485
    max: 1500
  - steel_type: "18G2SHF"
    min: 1525
    max: 1540
  - steel_type: "20GST"
    min: 1530
    max: 1545
  - steel_type: "20KP"
    min: 1540
    max: 1555
  - steel_type: "23GS"
    min: 1530
    max: 1545
  - steel_type: "25G2S"
    min: 1535
    max: 1550
  - steel_type: "3G1SP"
    min: 1535
    max: 1550
  - steel_type: "3GSP"
    min: 1535
    max: 1550
  - steel_type: "5G1SP"
    min: 1530
    max: 1545
  - steel_type: "5G2SP"
    min: 1525
    max: 1540
  - steel_type: "5GSP"
    min: 1530
    max: 1545
  - steel_type: "G4Si1"
    min: 1540
    max: 1550
  - steel_type: "ST3PS"
    min: 1535
    max: 1550
  - steel_type: "ST3SP"
    min: 1538
    max: 1553
  - steel_type: "ST5SP"
    min: 1525
    max: 1545
  - steel_type: "ST6SP"
    min: 1515
    max: 1530
  - steel_type: "SV-08G2S"
    min: 1540
    max: 1550
  - steel_type: "3GPS"
    min: 1535
    max: 1550
  - steel_type: "35ГCM"
    min: 1530
    max: 1545
  - steel_type: "CТ3CSP"
    min: 1538
    max: 1553
  - steel_type: "CТ3CSP-1"
    min: 1538
    max: 1553
  - steel_type: "CТ3Г1CSP"
    min: 1535
    max: 1550
  - steel_type: "CТ3ГCSP"
    min: 1535
    max: 1550
  - steel_type: "CТ4CSP"
    min: 1530
    max: 1545
  - steel_type: "CТ5CSP"
    min: 1525
    max: 1545
  - steel_type: "CТ5Г1CSP"
    min: 1530
    max: 1545
  - steel_type: "CТ5ГCSP"
    min: 1530
    max: 1545
  - steel_type: "SAE 1008"
    min: 1555
    max: 1570
  - steel_type: "SAE 1022"
    min: 1540
    max: 1555
  - steel_type: "SAE 1030"
    min: 1520
    max: 1535
  - steel_type: "SAE 1040"
    min: 1515
    max: 1530
  - steel_type: "SAE 1045"
    min: 1510
    max: 1525
  - steel_type: "SAE 1006"
    min: 1555
    max: 1570
  - steel_type: "CТ3ПC"
    min: 1538
    max: 1553
