mssql_data_bof:
  server: KRR-TST-PAHWL02
  user_id: EUROPE\aadzenzura
  password: h)#X2Ubu04Qm2
  database: KRR-PA-DEV-Development

postgres_raw_data:
  host: krr-sql-pgnode01
  port: 5432
  user: aadzenzura
  password: h)#X2Ubu04Qm2
  dbname: krr-pa-raw-data
  sslmode: disable

postgres_dev:
  host: krr-sql-pgnode01
  port: 5432
  user: aadzenzura
  password: h)#X2Ubu04Qm2
  dbname: development
  sslmode: disable

type_ms: "mssql"
type_pg: "postgres"

querries:
  consumption_mnlz: "SELECT * FROM public.cast_iron_consumption_mnlz('%s')"
  consumption_ingot: "SELECT * FROM public.cast_iron_consumption_ingot('%s')"
  meltdowns_casting: "SELECT * FROM public.number_of_meltdowns_casting('%s')"
  meltdowns_onrs: "SELECT * FROM public.number_of_meltdowns_onrs('%s')"
  scrap_consumption_mnlz: "SELECT * FROM public.scrap_consumption_mnlz('%s')"
  scrap_consumption_ingot: "SELECT * FROM public.scrap_consumption_ingot('%s')"
  si_in_cast_iron: "SELECT * FROM public.get_si_in_cast_iron('%s')"
  cast_iron_temperature: "SELECT * FROM public.get_cast_iron_temperature('%s')"
  s_content_percentage: "SELECT * FROM public.s_content_percentage('%s')"
  mnlz_production: "SELECT * FROM public.mnlz_production('%s')"
  ingot_production: "SELECT * FROM public.ingot_production('%s')"
  o2_content_at_the_outlet: "SELECT * FROM public.o2_content_at_the_outlet('%s')"
  get_lime: "SELECT * FROM public.get_lime('%s')"
  get_dolomite: "SELECT * FROM public.get_dolomite('%s')"
  get_aluminum: "SELECT * FROM public.get_aluminum('%s')"
  get_mixture: "SELECT * FROM public.get_mixture('%s')"