package models

type Report struct {
	Id                     int     `stbl:"\"Id\", PRIMARY_KEY, SERIAL"`
	Date                   string  `stbl:"\"Date\""`
	CastIronMelting        float64 `stbl:"\"CastIronMelting\""`
	ScrapMelting           float64 `stbl:"\"ScrapMelting\""`
	SiInCastIron           float64 `stbl:"\"SiInCastIron\""`
	CastIronTemperature    int     `stbl:"\"CastIronTemperature\""`
	GoodCastIron           float64 `stbl:"\"GoodCastIron\""`
	SContent               float64 `stbl:"\"SContent\""`
	MNLZMelting            float64 `stbl:"\"MNLZMelting\""`
	IngotMelting           float64 `stbl:"\"IngotMelting\""`
	O2Content              int     `stbl:"\"O2Content\""`
	LimestoneFlow          float64 `stbl:"\"LimestoneFlow\""`
	DolomiteFlow           float64 `stbl:"\"DolomiteFlow\""`
	AluminumPreheating     float64 `stbl:"\"AluminumPreheating\""`
	MixMelting             float64 `stbl:"\"MixMelting\""`
	SiCC                   float64 `stbl:"\"SiCC\""`
	SiModel                float64 `stbl:"\"SiModel\""`
	SiMnCC                 float64 `stbl:"\"SiMnCC\""`
	SiMnModel              float64 `stbl:"\"SiMnModel\""`
	MnCC                   float64 `stbl:"\"MnCC\""`
	MnModel                float64 `stbl:"\"MnModel\""`
	SlagTruncationRatio    float64 `stbl:"\"SlagTruncationRatio\""`
	SlagSkimmingRatio      float64 `stbl:"\"SlagSkimmingRatio\""`
	CCMeltingCycle         int     `stbl:"\"CCMeltingCycle\""`
	FePercentageInSlag     float64 `stbl:"\"FePercentageInSlag\""`
	SlagSamplingPercentage float64 `stbl:"\"SlagSamplingPercentage\""`
	GoodCCOutput           float64 `stbl:"\"GoodCCOutput\""`
	GoodCCMNLZOutput       float64 `stbl:"\"GoodCCMNLZOutput\""`
	GoodIngotOutput        float64 `stbl:"\"GoodIngotOutput\""`
	ProcessingTime         int     `stbl:"\"ProcessingTime\""`
	ArcTime                int     `stbl:"\"ArcTime\""`
	LimestoneConsumption   float64 `stbl:"\"LimestoneConsumption\""`
	FluorsparConsumption   float64 `stbl:"\"FluorsparConsumption\""`
	ArgonOxygenConsumption float64 `stbl:"\"ArgonOxygenConsumption\""`
	ElectricityConsumption float64 `stbl:"\"ElectricityConsumption\""`
	ElectrodeConsumption   float64 `stbl:"\"ElectrodeConsumption\""`
	InletTemperature       int     `stbl:"\"InletTemperature\""`
	InletOxidation         int     `stbl:"\"InletOxidation\""`
	UPKSlagAnalysis        float64 `stbl:"\"UPKSlagAnalysis\""`
	CastingCycle           int     `stbl:"\"CastingCycle\""`
	CastingSpeed           float64 `stbl:"\"CastingSpeed\""`
	CastingStopperSerial   float64 `stbl:"\"CastingStopperSerial\""`
	MNLZ1OpenSerial        float64 `stbl:"\"MNLZ1OpenSerial\""`
	MNLZ2OpenSerial        float64 `stbl:"\"MNLZ2OpenSerial\""`
	MNLZ3OpenSerial        float64 `stbl:"\"MNLZ3OpenSerial\""`
	MNLZ1Streams           float64 `stbl:"\"MNLZ1Streams\""`
	MNLZ2Streams           float64 `stbl:"\"MNLZ2Streams\""`
	MNLZ3Streams           float64 `stbl:"\"MNLZ3Streams\""`
	MNLZ1RepackingDuration float64 `stbl:"\"MNLZ1RepackingDuration\""`
	MNLZ2RepackingDuration float64 `stbl:"\"MNLZ2RepackingDuration\""`
	MNLZ3RepackingDuration float64 `stbl:"\"MNLZ3RepackingDuration\""`
	MNLZ1MeltTempDeviation float64 `stbl:"\"MNLZ1MeltTempDeviation\""`
	MNLZ2MeltTempDeviation float64 `stbl:"\"MNLZ2MeltTempDeviation\""`
	MNLZ3MeltTempDeviation float64 `stbl:"\"MNLZ3MeltTempDeviation\""`
	GoodMNLZOutput         float64 `stbl:"\"GoodMNLZOutput\""`
	MetalRetentionTime     int     `stbl:"\"MetalRetentionTime\""`
	ReportType             string  `stbl:"\"ReportType\""`
}
